services:
  app:
    image: ghcr.io/couseran/website:main
    restart: unless-stopped
    networks:
      - proxy
    environment:
      TZ: "Europe/Paris"
    labels:
      traefik.enable: true
      traefik.http.routers.website.rule: "HostRegexp(`^(?:www\.)?couseran\.fr$`)"

networks:
  proxy:
    external: true
